# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# The default language is set to en
en:
  languageCode: en-us
  contentDir: content/en
  title: Canteli
  params:
    description: Anderson Marcos Dias Canteli's resume
    
pt:
 languageCode: pt-br
 contentDir: content/pt
 title: Canteli
 params:
  description: Currículo de Anderson Marcos Dias Canteli


